name: project
properties:
- name: workplace_onsite
  type: boolean
- name: workplace_online
  type: boolean
- name: deadline
  type: date
- name: budget
  type: float
- name: state
  type: string
- name: description
  type: string
